version: '3.8'

services:

  crawler-service:
    build:
      context: ../
      dockerfile: ./stack/python/Dockerfile
      target: ${DOCKER_TARGET:-base}
    depends_on:
      database-service:
        condition: service_healthy

  database-service:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8889:80
    environment:
      - PMA_HOST=${DATABASE_HOST}
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASSWORD}